version: '3.8'

services:
  # db:
  #   image: postgres:13
  #   ports:
  #     - '5432:5432'
  #   env_file:
  #     - .env.docker

  monolith:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   - db
    env_file:
      - .env.docker
    command: >
      sh -c "
      pnpm prisma generate &&
      pnpm prisma migrate dev --name init &&
      pnpm prisma migrate deploy &&
      pnpm start:dev
      "
