version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - .env

  monolith:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      until nc -z db 5432; do 
        echo 'Waiting for Postgres...'; 
        sleep 2; 
      done && 
      pnpm prisma generate &&
      pnpm prisma migrate dev && 
      pnpm prisma migrate deploy && 
      pnpm start:dev
      "
